### PR TITLE
fix bug in sample_with_array

### PR DESCRIPTION
**Pull request by liangt**

### CODE REVIEW

**Comment by liangt** [comment]
https://github.com/mdbloice/Augmentor/issues/90

**Comment by mdbloice** [comment]
Hi @liangt, thanks for the PR, I will take a look at it closely and see if we can merge it. I think I'd also like to provide an option to allow for either and array-like object to be returned or a PIL image.

**Comment by liangt** [comment]
Hi @mdbloice, thanks for your reply. I just did the easiest change to make make sample_with_array work and I did not consider it fully, so I think it's better if you give a complete consideration of how it should be fixed and what function it provides.  :smiley::smiley:

**Comment by mdbloice** [comment]
@liangt yeah sure, no probs, thanks again for the efforts.

**Pull request closed without merging**
