### PR TITLE
Add PyTorch support in Pipeline class

### PR DESCRIPTION
**Pull request by juneoh**
This is a re-post of pull request #45. Build failure is now fixed, but .travis.yml became messy, for:
- torchvision is not on PyPI, only on Anaconda
- torchvision supports only Python 2.7, 3.5, and 3.6

### CODE REVIEW

**Comment by mdbloice** [comment]
That's real nice work with this new PR!

**Comment by juneoh** [comment]
Thanks for the quick merge! Now I'll be able to persuade my colleagues to use this.

**Comment by mdbloice** [comment]
Nice! Spread the word :-) 
PS because this is quite a nice feature to have, I will update Augmentor to version 0.1.6 and put that version on the PyPI, so that current installs will get updated by pip (and of course will be included in any new installs). 
M.

**Comment by mdbloice** [comment]
OK so this is now done, @juneoh . Your PR is part of version 0.1.6 (now live on PyPI) and the `README.md` has also been updated to reflect the ability to use Augmentor with PyTorch. Thanks again for the input!

**Comment by juneoh** [comment]
Wow, it must be Christmas already! I’ll share the good news with the PyTorch community in my neighborhood. Thanks so much :)

**Pull request merged**
